### ISSUE TITLE
Compilation error with generics

### ISSUE THREAD

**Issue by jscharett** [leandreck/spring-typescript-services#60]
Getting the an error when trying to use Generics in a return type like so:

```
@Data
@NoArgsConstructor
public class PagedContent<T>{
	private T content;
	private int totalRecords;
}

public PagedContent<ImportList> getImportList(...
```

```
[ERROR] Unkown Error occured, please file a Bug https://github.com/leandreck/spring-typescript-services/issues
[ERROR]   java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$TypeVariableSymbol cannot be cast to javax.lang.model.element.TypeElement
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.getDefiningClassElement(TypeNodeFactory.java:187)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.initType(TypeNodeFactory.java:151)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.createTypeNode(TypeNodeFactory.java:136)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.lambda$defineChildren$13(TypeNodeFactory.java:243)
[ERROR]         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[ERROR]         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[ERROR]         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[ERROR]         at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[ERROR]         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[ERROR]         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[ERROR]         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[ERROR]         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[ERROR]         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.defineChildren(TypeNodeFactory.java:244)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.initType(TypeNodeFactory.java:158)
[ERROR]         at org.leandreck.endpoints.processor.model.TypeNodeFactory.createTypeNode(TypeNodeFactory.java:109)
[ERROR]         at org.leandreck.endpoints.processor.model.MethodNodeFactory.defineReturnType(MethodNodeFactory.java:76)
[ERROR]         at org.leandreck.endpoints.processor.model.MethodNodeFactory.createMethodNode(MethodNodeFactory.java:64)
[ERROR]         at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[ERROR]         at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[ERROR]         at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
[ERROR]         at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
[ERROR]         at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[ERROR]         at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]         at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[ERROR]         at org.leandreck.endpoints.processor.model.EndpointNodeFactory.defineMethods(EndpointNodeFactory.java:61)
[ERROR]         at org.leandreck.endpoints.processor.model.EndpointNodeFactory.createEndpointNode(EndpointNodeFactory.java:52)
[ERROR]         at org.leandreck.endpoints.processor.TypeScriptEndpointProcessor.processEndpoints(TypeScriptEndpointProcessor.java:120)
[ERROR]         at org.leandreck.endpoints.processor.TypeScriptEndpointProcessor.process(TypeScriptEndpointProcessor.java:96)
[ERROR]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
[ERROR]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
[ERROR]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[ERROR]         at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
[ERROR]         at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
[ERROR]         at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[ERROR]         at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[ERROR]         at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[ERROR]         at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
[ERROR]         at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
[ERROR]         at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1075)
[ERROR]         at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:168)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by jscharett** [comment]
Any update here?

**Comment by mkowalzik** [comment]
Hi jscharett, thank you for your patience.
This bug is related to the lack of correct support for generics.
Fixing it without support for Generics on the TypeScript side would be much easier but would lose the valuable typings, so I am currently in the middle of a major rewrite to support them. Which may or will also be part of the solution to Optional<?>. Generics are a beast and add a whole new level of complexity because now you have declared Types and context-dependent bounded ones.
I think it wíll be done within the next two weeks depending on the spare time I can find.
Do you have urgent needs for a fix?

**Comment by jscharett** [comment]
Cool, thanks for the update.  Nothing pressing at the moment.

**Comment by mkowalzik** [comment]
Hi @jscharett, the current SNAPSHOT is able to process Optional and has a basic support for Generics. That means it generates generic TypeScript Interfaces but the Variable Symbols are without bounds. See https://github.com/leandreck/spring-typescript-services/blob/development/examples/src/main/java/org/leandreck/endpoints/examples/lombok/LombokResponse.java which generates:

export interface LombokResponse<T, X, Y, Z, B> {
size: number;
listWithTypeBElements: T;
listWithSuperTypesOfY: X;
typeY: Y;
typeZ: Z;
}

**Comment by jscharett** [comment]
Checked out the latest, and there looks to be some issues.  First, the generated interfaces all seem to import themselves.  For example

```
import { ClassA } from './classA.model.generated';

export interface ClassA {
    id: number;
}
```

Second, my model using generics is not being output as expected.  Its partially replacing the generic with a specific type.  

```
package a.b.c.model;

import java.util.List;

import lombok.Data;
import lombok.NonNull;

@Data
public class ClassA<T> {
	@NonNull private List<T> content;
	@NonNull private int totalRecords;
}
-----------------------------------------------------------------------
package a.b.c.controller;

import org.leandreck.endpoints.annotations.TypeScriptEndpoint;

import java.util.Optional;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.core.Context;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.MediaType;

import a.b.c.model.ClassA;
import a.b.c.model.ClassB;

@TypeScriptEndpoint(template = "/src/main/resources/service.ftl")
@RestController
@RequestMapping("path")
public class RestController {
	@RequestMapping(method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	public ClassA<ClassB> getAB(
		@RequestParam("startIndex") Optional<Integer> startIndex,
		@RequestParam("recordCount") Optional<Integer> recordCount,
		@RequestParam("sortFields") Optional<String> sortFields,
		@RequestParam("filter") Optional<String> filter,
		@Context HttpServletRequest request
	) throws Exception {....}
}
```
produces
```
import { ClassB } from './classB.model.generated';
import { ClassA } from './classA.model.generated';

export interface ClassA<T> {
content: ClassB[];
totalRecords: number;
}
-----------------------------------------------------------------
import { ClassA } from './classA.model.generated';
import { ClassB } from './classB.model.generated';

import { HttpClient, HttpParams, HttpRequest } from '@angular/common/http';
import { Injectable } from '@angular/core';

import { Observable } from 'rxjs/Observable';
import 'rxjs/add/operator/catch';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/map';

@Injectable()
export class RestController {
    private serviceBaseURL = 'path';
    constructor(private httpClient: HttpClient) { }
    /* GET */
    public getAB(startIndex?: any, recordCount?: any, sortFields?: any, filter?: any): Observable<ClassA<ClassB>> {
        const url = this.serviceBaseURL + '';
        const paramNames = ['startIndex', 'recordCount', 'sortFields', 'filter'];
        const paramValues = [startIndex, recordCount, sortFields, filter];
        const params = this.getHttpParams(paramNames, paramValues);
        return this.httpClient.get<ClassA<ClassB>>(url, {params: params})
            .catch((error: Response) => this.handleError(error));
    }
}
```
Note: I'm using a custom service.ftl, so the generated service class may look different.

If you look at the generated interface, its not correct.  The content should be of type T, should it not? The interface should have no knowledge of ClassB.

**Comment by mkowalzik** [comment]
Yes, you are completely right and there are some more related issues for example with Maps and Arrays, which I hopefully get fixed tomorrow.

**Comment by jscharett** [comment]
Hey, thanks for the hard work and getting this in.  Any idea on when it might officially land?  There is a lot of push my our services team to use ResponseEntity for our returns types, and since that uses generics, I assume this needs to land.  Not sure if this will allow for use of ResponseEntity, or if that's a new feature request.

**Comment by mkowalzik** [comment]
Hi, you are welcome. I have pushed a new snapshot with fixes.
ResponseEntity is working like Optional<T>, so it will output only the bound body as Type.
So you should be able to use 
```java
    @RequestMapping(value = "/foo/{idPathVariable}/{typeRef}", 
        method = POST, consumes = APPLICATION_JSON_VALUE, 
        produces = APPLICATION_JSON_VALUE)
    public ResponseEntity<LombokResponse<List<RootType>, List<Object>, Boolean, SubType, RootType>> 
        setResponseEntity(
            @PathVariable(name = "idPathVariable") Long id,
            @PathVariable String typeRef,
            @RequestParam(name = "queryRequestParam", required = false) Optional<String> queryParameter,
            @RequestBody(required = false) LombokRequest body) {
        // do something
        return ResponseEntity.ok(new LombokResponse<>());
    }
```
and generate
```javascript
    public setResponseEntityPost(idPathVariable: number, typeRef: string, body?: 
      LombokRequest, queryRequestParam?: string): 
      Observable<HttpResponse<LombokResponse<MyTypeScriptType[], any[], boolean, SubType, MyTypeScriptType>>> {
        const url = this.serviceBaseURL + '/foo/' + idPathVariable + '/' + typeRef + '';
        const params = new HttpParams().set('queryRequestParam', queryRequestParam);
        return this.httpClient.post<LombokResponse<MyTypeScriptType[], any[], boolean, SubType, MyTypeScriptType>>(url, body, {params: params})
            .catch((error: Response) => this.handleError(error));
    }
```

**Comment by mkowalzik** [comment]
@jscharett let me know whether everything works as expected or not.

**Comment by jscharett** [comment]
Will pull in and test tommorrow.

**Comment by jscharett** [comment]
There are some issues with 0.3.0.  I have a couple of complication errors with my serviceConfig stuff; working them out and will push tonight.  Also, looking at the endpoints that our project generates, they all seem to include an `body: any | null`, though the parameter is never used in the call.  If it needs to be there because we are specifying in the Java service, could it be at the end vs the first parameter?

**Comment by jscharett** [comment]
There is also an issue with setting HttpParams that are not strings, as the spec requires them to be strings.  I ran into this issue awhile ago, just forgot to put in an issue for it.  I've been getting around it locally with a helper function like so

```
private getHttpParams(keys, values): HttpParams {
    let httpParams = new HttpParams();

    values.forEach((value, index) => {
        if (value != null && value !== '') {
            httpParams = httpParams.set(keys[index], String(value));
        }
    });

    return httpParams;
}
```

It's not the cleanest solution, but has allowed me to work around it.

**Comment by mkowalzik** [comment]
@jscharett if you send me a pm I can invite you to our slack channel. That makes discussions over possible solutions much easier and faster.
